#!/usr/bin/python3
from sys import argv
from math import sqrt
filename = argv[1]

with open(filename, 'r') as file1:
    lines = file1.readlines()

for line in lines:
    big_num = int(line.strip())
 #   dub = []

    for i in range(2, int(sqrt(big_num)) + 1):
        if big_num % i == 0:
            num1 = big_num // i
            num2 = i
  #          dub.append(big_num)

   #         if len(dub) > 1:
    #            continue

            print(f"{big_num}={num1}*{num2}")
            break;
